### ISSUE TITLE
Basic Issue - Setup

### ISSUE THREAD

**Issue by cartoonmadrasah** [thetre97/gridsome-plugin-flexsearch#14]
I am not being able to generate any search results, I wonder what am I doing wrong here. Here is my setup. Kindly help. Thank you.

![Image 1](https://user-images.githubusercontent.com/7679807/71553630-c0d3e680-2a34-11ea-8cd2-69b7b7785fa3.png)

![Image 2](https://user-images.githubusercontent.com/7679807/71553647-ee209480-2a34-11ea-832e-e202fd60e492.png)

![Image 3](https://user-images.githubusercontent.com/7679807/71553666-3b9d0180-2a35-11ea-9014-02d786d45a24.png)

Thank you once again.

**Comment by thetre97** [comment]
Hello @cartoonmadrasah 

Do you possibly have a repo I could look at? If not, would you be able to show me the output of a query using that type? I.e.

```graphql
query {
  predubai (id: something) {
    Id
    Emirate
    ...etc
  }
}

```
Those search fields look as if they may be custom object types, rather than strings/IDs etc?

**Comment by cartoonmadrasah** [comment]
![Image 4](https://user-images.githubusercontent.com/7679807/71566287-3d6bd100-2ad8-11ea-9842-aa0c251b1572.png)

**Comment by thetre97** [comment]
Yes, as I thought those fields are actually objects - in your server file could you do `emirate: Item.emirate['_text']` for each field, so when you query `emirate` it will be a string? Then flexsearch should be able to index it.

**Comment by cartoonmadrasah** [comment]
I tried with the ID field. That did not work. I also tested it with one field using the method you suggested (company_name).

I followed the intructions as they were given but now I have basic question maybe that do I need to also import the library in the main.js or just by calling it on the gridsome.config.js sufficient.

**Comment by thetre97** [comment]
@cartoonmadrasah please use travis@travisreynolds.dev

The plugin will automatically configure the client for you, so you should just be able to use `this.$search` in your code (or import the included mixin).

**Comment by cartoonmadrasah** [comment]
I have added you to the repo.

**Comment by thetre97** [comment]
@cartoonmadrasah Just had a look at that repo, and it all seems to work?
![image](https://user-images.githubusercontent.com/12587127/71646342-e1bf6480-2cde-11ea-913b-9782ff8660d8.png)

searching for the ID won't work, as you need at least 3 characters to start searching... `if (searchTerm.length < 3) return []`  but searching for the company name should work.
Results won't show up in `Search.vue`, as you are trying to display `result.title` - try changing this to `result.company_name` for example.

**Comment by thetre97** [comment]
P.S. You could also loop through the object keys, converting them to snake case, and setting _text as the direct value:

```js
const { snakeCase } = require('snake-case')
for (const item of predata.Listings.Listing) {
    const doc = Object.entries(item).reduce((obj, [key, value]) => ({ [ snakeCase(key) ]: value._text, ...obj }), {})
    contentType.addNode(doc)
}
```

**Comment by cartoonmadrasah** [comment]
Oh wow, thank you so much.
