### ISSUE TITLE
Some Search Terms Not Returning An Expected Result

### ISSUE THREAD

**Issue by darrylmorley** [thetre97/gridsome-plugin-flexsearch#16]
Hi,

I have the titles of products added as a search field, whilst some results are returned, not all are. I'm not sure why that would be?

I have in my config:
```
{
      use: 'gridsome-plugin-flexsearch',
      options: {
        collections: [
          {
            typeName: 'Guns',
            indexName: 'Guns',
            fields: ['title', 'slug', 'images', 'price', 'mechanism', 'id']
          }
        ],
        searchFields: ['title', 'mechanism']
      }
    }

Some title's are returned whilst others are not.

**Comment by thetre97** [comment]
Sorry - as in titles are being returned in some of the search results, while others aren't? Or some items aren't being found at all by the search?

**Comment by darrylmorley** [comment]
Sorry, I didn't explain clearly. Titles are not being found by the search.

**Comment by thetre97** [comment]
Have you tried different flexsearch profiles? For instance:

```js
{
      use: 'gridsome-plugin-flexsearch',
      options: {
        flexsearch: {
          profile: 'match'
        },
        collections: [
          {
            typeName: 'Guns',
            indexName: 'Guns',
            fields: ['title', 'slug', 'images', 'price', 'mechanism', 'id']
          }
        ],
        searchFields: ['title', 'mechanism']
      }
    }
```

See https://github.com/nextapps-de/flexsearch#presets for more examples

**Comment by darrylmorley** [comment]
I haven't, I'll give it a try. Thanks.

**Comment by darrylmorley** [comment]
The issue appears only when built on Netlify?

**Comment by thetre97** [comment]
That's very strange - no, I haven't had any issues before. Would you be able to send the site url, so I could have a look?

**Comment by thetre97** [comment]
For example, https://gridsome-shopify-starter.netlify.com seems to work fine...

**Comment by thetre97** [comment]
I take that back - just checked https://gridsome-shopify-starter.netlify.com, and it seems to have the same issue - nothing is shown at all when I try to search... I'll have a deeper look into this.

**Comment by darrylmorley** [comment]
Sure, the site is guns.shootingsuppliesltd.co.uk

So if you type 'ber' for beretta, it will work.
But, if you type 'chi' fir chiappa it won't.

**Comment by thetre97** [comment]
Just checked the console on yours, and it seems to be throwing an  error - `TypeError: Cannot read property 'FullPath' of undefined`

Perhaps that is why it won't show some results?

**Comment by darrylmorley** [comment]
No, I've managed to handle that. 

Netlify used to fail to build if the api I'm pulling from didn't have an image attached to the product. That's what that error refers to.

**Comment by thetre97** [comment]
Okay, but just to check - say there are no images in that array `:v-if="result.images[0].FullPath"`, then FullPath will be undefined - hence the error?
Could you try checking for `:v-if="result.images.length"`?

**Comment by darrylmorley** [comment]
I have in my server.config:

```
 api.onCreateNode(options => {
    if (options.internal.typeName === "Guns" && options.imageCount === 0) {
      // return null to filter it out
      return null;
    }
  });

**Comment by thetre97** [comment]
Hmm, okay - and that does correctly filter it out? If so then that condition should work...
What does `console.log(options)` look like?

This was in the chrome console, when visiting the site.

**Comment by darrylmorley** [comment]
Hmm, 
It should have worked.. lol. The builds used to fail before.
Clearly, there is still an issue here on my end.

**Comment by thetre97** [comment]
Sorry, I meant in `api.onCreateNode(options => {`...

**Comment by darrylmorley** [comment]
Yep, I'm still getting a load of empty arrays :(

**Comment by thetre97** [comment]
Ah, just had a thought - the plugin hooks into `onCreateNode`, so probably gets all the nodes before they have been filtered out.
you could try a couple of things - either do:

```js
for (const item of data.Guns) {
      if (item.ImageCount === 0) continue # skip this iteration, will never add to the store
      guns.addNode({
        ...
```

Or filter the results using the images length in your search component:

`<figure v-if="result.images.length">`

Or
```js
computed: {
    searchResults () {
      const searchTerm = this.searchTerm
      if (searchTerm.length < 3) return []
      const results = this.$search.search({ query: searchTerm, limit: 100 })
      return results.filter(result => result.images.length)
    },
  }
```

**Comment by darrylmorley** [comment]
That's fixed it:
```
for (const item of data.Guns) {
      if (!item.ImageCount) continue # skip this iteration, will never add to the store
      guns.addNode({
        ...
```
Sorry, this wasn't really a plugin issue in the end, more my own. I appreciate your help! Thank you.

**Comment by thetre97** [comment]
No worries, you're welcome! 👍
