### ISSUE TITLE
Version:0.1.11 - flexsearch.json 404

### ISSUE THREAD

**Issue by chenhongen** [thetre97/gridsome-plugin-flexsearch#19]
when I upgrade to 0.1.11,It can't work and show
 "gridsome.client.js?aebf:3 GET http://localhost:8081/cheese/flexsearch.json 404 (Not Found)" in console.
![image](https://user-images.githubusercontent.com/16499303/73232097-17ac1780-41bd-11ea-80f5-ec532eea1d77.png)

**Comment by chenhongen** [comment]
And after clean npm cache

**Comment by thetre97** [comment]
Sorry for this - could I ask if you have a `pathPrefix` set in your `gridsome.config.js`? If so, it may be that it is trying to use that in development, when it shouldn't.

**Comment by chenhongen** [comment]
Yes,I set "pathPrefix" in` gridsome.config.js`.It can use normal under version of 0.1.10 in development .But when I deploy it to my site,`flexsearch.json `lose the prefix path again.like this:
![image](https://user-images.githubusercontent.com/16499303/73263180-f2de9100-420a-11ea-8ecd-76658b9a1653.png)

**Comment by chenhongen** [comment]
So, my question is that with "pathPrefix" in `gridsome.config.js`：
                                0.1.10                 0.1.11 
development             √                         x
production                 x                         √

**Comment by chenhongen** [comment]
So, my question is that with "pathPrefix" in `gridsome.config.js`：
development  0.1.10【√】    0.1.11 【x】
production      0.1.10【x】    0.1.11 【√】

**Comment by thetre97** [comment]
I have just published `0.1.12`, which should contain a fix for this. Could you let me know if that works correctly?

**Comment by chenhongen** [comment]
When I upgraded to `0.1.12`,It worked well in both environment.Thanks
