### ISSUE TITLE
Can't search on multiple terms

### ISSUE THREAD

**Issue by kayakmind** [thetre97/gridsome-plugin-flexsearch#3]
Thanks for this plugin. I've got it mostly working, but the input field will only accept one word. If I type more than one, no results show. For example, if I type "Dog" get results, but if I type "Dog eats, " I don't get anything.

**Comment by thetre97** [comment]
This issue seems to suggest this may be a bug: https://github.com/nextapps-de/flexsearch/issues/96
However, a quick and easy solution might be to add suggest to the search query:

```js
export default {
  data: () => ({
    searchTerm: ''
  }),
  computed: {
    searchResults () {
      const searchTerm = this.searchTerm
      if (searchTerm.length < 3) return []
      return this.$search.search({ query: searchTerm, limit: 5, suggest: true })
    }
  }
}
```

**Comment by thetre97** [comment]
Edit: I just noticed I wasn't actually passing those options in to the client-side plugin properly, so have just released 0.1.8 that should fix this, and multi word search should work properly with the default preset.

**Comment by kayakmind** [comment]
Thanks Travis! I'll give it a try.

**Comment by kayakmind** [comment]
It's working. Thanks!
