### ISSUE TITLE
"TypeError: Cannot read property 'search' of undefined"

### ISSUE THREAD

**Issue by gridsome-user** [thetre97/gridsome-plugin-flexsearch#31]
I deployed gridsome-plugin-flexsearch.

I updated the gridsome.config.js file with:

>    use: 'gridsome-plugin-flexsearch',
>    options: {
>       collections: [
>         {
>           typeName: 'Post',
>           indexName: 'Post',
>           fields: ['title', 'description']
>         }
>       ],
>       searchFields: ['title']
>     }

I added the blocks below on my vue page:
```
 <input      
    id="search"
      v-model="searchTerm"
      class="input"
      type="text"
      placeholder="Search">
    <g-link
      v-for="result in searchResults"
      :key="result.id"
      :to="result.path"
      class="navbar-item">
      {{ result.title }}
    </g-link>
```

```
  data: () => ({
    searchTerm: ''
  }),
  computed: {
    searchResults () {
      const searchTerm = this.searchTerm
      if (searchTerm.length < 3) return []
      return this.$search.search({ query: searchTerm, limit: 5 })
    }
  }
```

My Graphql query is
```
`<page-query>
query {
  metadata {
    siteName
  }
  posts: allPost {
    edges {
      node {
        id
        title
        resume
        timeToRead
        description
        date (format: "DD/MM/YYYY")
        path
        image
      }
    }
  }
}
</page-query>`
```

When I tried to access to this page, I have errors:

> [Vue warn]: Error in render: "TypeError: Cannot read property 'search' of undefined"

```
vue.runtime.esm.js?2b0e:1888 TypeError: Cannot read property 'search' of undefined
    at VueComponent.searchResults (Vols.vue?2d49:72)
    at Watcher.get (vue.runtime.esm.js?2b0e:4479)
    at Watcher.evaluate (vue.runtime.esm.js?2b0e:4584)
    at VueComponent.computedGetter [as searchResults] (vue.runtime.esm.js?2b0e:4836)
    at Object.get (vue.runtime.esm.js?2b0e:2072)
    at Proxy.render (eval at ./node_modules/cache-loader/dist/cjs.js?
```

It seems the Search function is not recognized.

**Comment by thetre97** [comment]
@gridsome-user Did you try it with the mixin? And could I check what version of the plugin you are using?

I did use to get that error as it took a while for the Flexsearch instance to setup, but I thought I had fixed that. If you could provide a demo repo I could look at where that error happens, it would be great.

**Comment by gridsome-user** [comment]
I have the same issue with Mixin.
I use the last version 0.1.18
I have Gridsome  v0.7.13

When I installed it, I had this warning:

> npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

I will try to provide you a demo repo.

**Comment by thetre97** [comment]
@gridsome-user Are you still having this issue? I have released a new version since this issue, could you try that if so?
