### ISSUE TITLE
Use with the @paginate directive

### ISSUE THREAD

**Issue by arincon9** [thetre97/gridsome-plugin-flexsearch#32]
How would I use this plugin with the `@paginate` directive?

I essentially want to paginate the results from the flexsearch.

**Comment by thetre97** [comment]
You wouldn't be able to use the Gridsome paginate directive, but Flexsearch does have built-in pagination - see: https://github.com/nextapps-de/flexsearch#pagination.

**Comment by thetre97** [comment]
@arincon9 Did the above help?
