### ISSUE TITLE
Wrong result index when searching in more than one collection?

### ISSUE THREAD

**Issue by Schoell** [thetre97/gridsome-plugin-flexsearch#34]
I want to search in more than one collection - for example:

    use: 'gridsome-plugin-flexsearch',
    options: {
    collections: [
        {
          typeName: 'Faqs',
          indexName: 'Faqs',
          fields: ['question', 'answer']
        },
        {
          typeName: 'Topics',
          indexName: 'Topics',
          fields: ['title', 'content']
        }
    ],
    searchFields: ['question', 'answer', 'title']
    }}

The wrong results are returned

e.g. item with id=3, but the wrong collection

     { "index": "Faqs", "id": "3",

instead of

    { "index": "Topics", "id": "3",

Any idea?

**Comment by thetre97** [comment]
So just to ensure I understand you correctly - in your data, there could potentially be two items with the id 3, but have different types...?

You should be able to specify a stricter search if needed, using https://github.com/nextapps-de/flexsearch#where, so you could specify that index = Topics.

**Comment by Schoell** [comment]
> So just to ensure I understand you correctly - in your data, there could potentially be two items with the id 3, but have different types...?
> 
yes, we use Directus CMS as data source The IDs of the nodes are assigned individually per collection. Therefore there are always nodes with the same ID of a certain collection. 

>You should be able to specify a stricter search if needed, using https://github.com/nextapps-de/flexsearch#where, so you could specify that index = Topics.

Is this possible, using you plugin?

**Comment by thetre97** [comment]
@Schoell It is, yes - you will just need to update your search function. I.e:

```js
this.$search.search(searchTerm,  {
    where: {
        "index": "some-index"
    },
    limit: 10
})
```

**Comment by Schoell** [comment]
The problem is the same ID in the search index. That means there is a FAQ with ID 1 and a TOPIC with ID 1. To solve the problem, the IDs must be extended by the collection type. 

I.e. FAQ with ID FAQ1 and TOPIC with ID TOPIC1.

In the gridsome.server.js in line 56 I have extended the IDs. With this it works.

      const doc = {
        index: index.indexName,
        id: node.id+index.indexName,
        path: node.path,
        ...docFields
      }

**Comment by thetre97** [comment]
Ah, I get your problem now. Could you use `onCreateNode` to edit your id's as above?

**Comment by PeterSchoell** [comment]
> Ah, I get your problem now. Could you use `onCreateNode` to edit your id's as above?

No, because we create the nodes using the Directus Plugin. But with the modification above it works fine.

**Comment by thetre97** [comment]
Even when using a source plugin, you can use the `onCreateNode` api to edit nodes - but if your solution works, then that's fine.
