### ISSUE TITLE
Strange Issue trying to return url from searchResults array.

### ISSUE THREAD

**Issue by darrylmorley** [thetre97/gridsome-plugin-flexsearch#38]
Hi,

I have a really weird issue. I have the below available in my searchResults array.
```
images:"[{"Number":1,"FullPath":"https://images.guntrader.uk/GunImages/19/1911/19112/191128124520003/191128124520003-1.jpg","ThumbPath":"https://images.guntrader.uk/GunImages/Thumbnails/191128124520003-1-120x120.jpg"},{"Number":2,"FullPath":"https://images.guntrader.uk/GunImages/19/1911/19112/191128124520003/191128124520003-2.jpg","ThumbPath":"https://images.guntrader.uk/GunImages/Thumbnails/191128124520003-2-120x120.jpg"}]"
```
When I try to select an image to display in my search results, it selects the characters rather than the url.
I have  ```<g-image :src="`${result.images[0].FullPath}`" :alt="`${result.title}`" />``` to select my image, this returns undefined.
If I change this a little to ```<g-image :src="`${result.images[0]}`" :alt="`${result.title}`" />``` I receive "[".

I am getting characters instead of the object?

**Comment by thetre97** [comment]
Is that array the exact result you get from your search results? As you can see, it is actually a string - note the `"` either side of the array. So when you do `[0]`, it selects the first character. 

I'll have a look into this, as to why it isn't parsing the array properly. Could you paste your flexsearch config here please?

**Comment by darrylmorley** [comment]
Ahh yes I see, so it is. My config is:
```
{
      use: "gridsome-plugin-flexsearch",
      options: {
        collections: [
          {
            typeName: "Guns",
            indexName: "Guns",
            fields: [
              "title",
              "slug",
              "images",
              "price",
              "mechanism",
              "id",
              "variant",
              "condition",
              "calibre"
            ]
          }
        ],
        searchFields: ["title", "mechanism", "calibre"]
      }
    }
```

**Comment by thetre97** [comment]
I have fixed this in a new version (which includes a number of updates), but am awaiting for a PR in Gridsome. For now you could just do `JSON.parse(<result>.images)` which will return the array.

**Comment by darrylmorley** [comment]
Thanks for your help!

**Comment by thetre97** [comment]
Yes, sorry - I haven't actually released the update yet...

**Comment by darrylmorley** [comment]
Ha, I ran an update which upgraded your plugin I figured you had released it. Sorry.
