### ISSUE TITLE
Tags object

### ISSUE THREAD

**Issue by ramsesgarate** [thetre97/gridsome-plugin-flexsearch#51]
Currently this is my plugin configuration:

```js
{
      use: 'gridsome-plugin-flexsearch',
      options: {
        flexsearch: {
          cache: true,
          profile: 'match'
        },
        collections: [{
          typeName: 'Post',
          indexName: 'Post',
          fields: ['title', 'description', 'tags', 'date']
        }],
        searchFields: ['title', 'tags'],
      }
    }
```

Is there any way that the tag output would look like this?
```json
[
  {
    "id":"markdown",
    "title":"markdown",
    "path":"/tag/markdown/"
  },
  {
    "id":"test-files",
    "title":"test-files",
    "path":"/tag/test-files/"
  }
]
```

Currently returns an array with only the title
```json
[
  "markdown",
  "test-files"
]
```

I was trying to use a query like I suggested on the plugin page, but I think I didn't configure it well, because it doesn't generate any results for me, so I decided to continue with the normal configuration.

**Comment by thetre97** [comment]
@ramsesgarate Thanks for reporting this. I hadn't tested it with the source filesystem -> refs config, it seems that it creates that relation after this plugin fetches the nodes. I'll try and take a look at this.

**Comment by thetre97** [comment]
@ramsesgarate I have made some updates to this plugin on the `graphql` branch - if you get the time, could you check to see if it fixes this issue for you?
