### ISSUE TITLE
Not work with Cyrillic

### ISSUE THREAD

**Issue by hqdrone** [thetre97/gridsome-plugin-flexsearch#53]
Hi, I'm from Russia and want to add flexsearch plugin on my Gridsome blog(https://frontips.ru/) but it's not work with Cyrillic encode

If I type text on English language I get result but if I type on Russian language Post Title not founding

```javascript
{
  use: 'gridsome-plugin-flexsearch',
  options: {
    searchFields: ['title'],
    collections: [
      {
        typeName: 'Post',
        indexName: 'Post',
        fields: ['title']
      }
    ]
  }
}
```

How can I solve this problem?

**Comment by thetre97** [comment]
Hello @hqdrone 

Please check the FlexSearch documentation for this - for example https://github.com/nextapps-de/flexsearch/issues/51.

You can also probably follow similar steps to #23
