### ISSUE TITLE
 How to make it work with Contentful Source

### ISSUE THREAD

**Issue by jrpersico-spurred** [thetre97/gridsome-plugin-flexsearch#63]
First of all thank you for this great plugin!

Can you tell me how to make it work with Contentful Source?

**Comment by thetre97** [comment]
Hey @jrpersico-spurred, you should be able to use it as usual, you just need to configure the correct types to add - you can see available types by checking the GraphQL explorer. For example, you may have `ContentfulPost`, which you would then configure like so:
```js
{
	use: 'gridsome-plugin-flexsearch',
	options: {
		searchFields: ['title'],
        collections: [
          {
            typeName: 'ContentfulPost',
            indexName: 'Post',
            fields: ['title', 'handle', 'description']
          }
        ]
  	}
}
```

**Comment by jrpersico-spurred** [comment]
Thank you for your reply.

I had misunderstood how to set indexName and typeName.
