### ISSUE TITLE
v2 Causes undefined Error

### ISSUE THREAD

**Issue by RehanSaeed** [thetre97/gridsome-plugin-flexsearch#71]
I'm trying to upgrade to v2 and am getting the following error upon building:

![image](https://user-images.githubusercontent.com/2270364/118245873-32c99600-b499-11eb-95a8-cde3a4a6e462.png)

**Comment by thetre97** [comment]
Hey @RehanSaeed - Would you mind posting your `gridsome.config.js` please?

**Comment by RehanSaeed** [comment]
It's all on GitHub here:
https://github.com/RehanSaeed/rehansaeed.github.io/blob/main/gridsome.config.js

**Comment by thetre97** [comment]
Sorry for the delay on this. Have just fixed the issue though, and released a patch version - `2.0.1`.
I've tested it out on your repo, and it seems to build okay now.

**Comment by RehanSaeed** [comment]
Gave 2.0.1 a try. It now compiles fine and I can search to get results back but the `result.path` or `result.node.permalink` values are `undefined`.

**Comment by mschmidtkorth** [comment]
Thanks a lot by the way for introducing the GraphQL layer, @thetre97!

**Comment by thetre97** [comment]
Ah, that is actually one big change I have made - apologies, I should have put that into the release notes.
The plugin doesn't automatically add the path field anymore, so you will have to add path or permalink to your collection fields, then you can access them from `node.<field>`.

**Comment by RehanSaeed** [comment]
That worked, thanks.
