### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by Samii-Noden** [thetre97/gridsome-plugin-flexsearch#73]
I'm not sure what I'm doing wrong here - I'm trying to transform the schema to enable searching in nested data structures but I just keep getting the above error.

gridsome.config.js 
![image](https://user-images.githubusercontent.com/67465800/128183163-4d0d6514-a67d-4fcf-b171-fbdb0581a80a.png)

error message received on 'gridsome develop'
![image](https://user-images.githubusercontent.com/67465800/128183283-31c577ec-07e7-4fc9-b187-89f8fe9b0647.png)

What haven't I done right?

**Comment by thetre97** [comment]
If you log `collection`, does it return an array of authors? IF so, could you paste what it does log?

**Comment by Samii-Noden** [comment]
I'm not sure I'm following, sorry. Log it in what way?

**Comment by thetre97** [comment]
Something like this:
```js
transform: (collection) => {
	console.log(collection)
	return {
		...collection,
		authors: collection.authors.map(author => author.name)
	}
}
```

**Comment by Samii-Noden** [comment]
Ah I see what you mean - the above code logs the whole object but only for one post(?). So it's returning everything from title to featuredMedia etc

The below is a test post with the error message at the bottom.

[Object: null prototype] {
  id: '7442',
  title: 'Yoast Post',
  slug: 'yoast-post',
  path: '/resources/news/yoast-post/',
  featuredMedia: [Object: null prototype] {
    id: '7560',
    date: '2021-07-29T13:50:17',
    dateGmt: '2021-07-29T13:50:17',
    guid: '/*removedorprivacyreasons*/',
    modified: '2021-07-29T13:50:31',
    modifiedGmt: '2021-07-29T13:50:31',
    slug: 'test-featured-image',
    status: 'inherit',
    type: 'attachment',
    link: '/*removedorprivacyreasons*/',
    title: 'test-featured-image',
    author: [Object: null prototype] {
      id: '1',
      name: 'Samii Noden',
      url: '/*removedorprivacyreasons*/',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lacinia at quis risus sed vulputate. Nunc pulvinar sapien et ligula 
ullamcorper. Ut sem nulla pharetra diam sit. Massa sapien faucibus et molestie ac. Lacus laoreet non curabitur gravida arcu. Vitae justo eget magna fermentum iaculis eu. Odio facilisis mauris sit amet massa vitae tortor. Eget nunc scelerisque viverra mauris in aliquam sem fringilla. Nulla posuere sollicitudin aliquam ultrices sagittis orci a. Leo a diam sollicitudin tempor id eu nisl nunc. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque.',
      link: '/*removedorprivacyreasons*/',
      slug: 'samiinoden',
      avatarUrls: [Object: null prototype],
      yoastHead: '\n' +
        '<title>Author | Samii Noden</title>\n' +
        '<meta name="robots" content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1" />\n' +
        '<link rel="canonical" href="/*removedorprivacyreasons*//" />\n' +
        '<meta property="og:locale" content="en_GB" />\n' +
        '<meta property="og:type" content="profile" />\n' +
        '<meta property="og:title" content="Author | Samii Noden" />\n' +
        '<meta property="og:url" content="/*removedorprivacyreasons*//" />\n' +
        '<meta property="og:site_name" content="US Resources - Gridsome" />\n' +
        '<meta property="og:image" content="/*removedorprivacyreasons*/" />\n' +
        '<meta name="twitter:card" content="summary_large_image" />\n' +
        '<script type="application/ld+json" class="yoast-schema-graph">{"@context":"https://schema.org","@graph":[{"@type":"WebSite","@id":"/*removedorprivacyreasons*//","name":"/*removedorprivacyreasons*/e","description":"Just another WordPress site","potentialAction":[{"@type":"SearchAction","target":"/*removedorprivacyreasons*//?s={search_term_string}","query-input":"required name=search_term_string"}],"inLanguage":"en-GB"},{"@type":"ProfilePage","@id":"/*removedorprivacyreasons*/","url":/*removedorprivacyreasons*/","name":"Author | Samii Noden","isPartOf":{"@id":"/*removedorprivacyreasons*/"},"breadcrumb":{"@id":"http:/*removedorprivacyreasons*/"},"inLanguage":"en-GB","potentialAction":[{"@type":"ReadAction","target":["/*removedorprivacyreasons*//"]}]},{"@type":"BreadcrumbList","@id":"/*removedorprivacyreasons*/","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"/*removedorprivacyreasons*//"},{"@type":"ListItem","position":2,"name":"Archives for Samii Noden"}]},{"@type":"Person","@id":"/*removedorprivacyreasons*/","name":"Samii Noden","image":{"@type":"ImageObject","@id":"/*removedorprivacyreasons*/","inLanguage":"en-GB","url":"/*removedorprivacyreasons*/","contentUrl":/*removedorprivacyreasons*/","caption":"Samii Noden"},"description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lacinia at quis risus sed vulputate. Nunc pulvinar sapien et ligula ullamcorper. Ut sem nulla pharetra diam sit. Massa sapien faucibus et molestie ac. Lacus laoreet non curabitur gravida arcu. Vitae justo eget magna fermentum iaculis eu. Odio facilisis mauris sit amet massa vitae tortor. Eget nunc scelerisque viverra mauris in aliquam sem fringilla. Nulla posuere sollicitudin aliquam ultrices sagittis orci a. Leo a diam sollicitudin tempor id eu nisl nunc. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque.","sameAs":["/*removedorprivacyreasons*/"],"mainEntityOfPage":{"@id":"/*removedorprivacyreasons*/e"}}]}</script>\n' +
        '',
      title: 'Samii Noden',
      avatars: [Object: null prototype],
      path: '/resources/author/samiinoden/'
    },
    commentStatus: 'open',
    pingStatus: 'closed',
    template: '',
    yoastHead: '\n' +
      '<title>/*removedorprivacyreasons*/</title>\n' +
      '<meta name="robots" content="noindex, follow" />\n' +
      '<meta property="og:locale" content="en_GB" />\n' +
      '<meta property="og:type" content="article" />\n' +
      '<meta property="og:title" content="/*removedorprivacyreasons*/" />\n' +
      '<meta property="og:url" content="/*removedorprivacyreasons*/" />\n' +
      '<meta property="og:site_name" content="/*removedorprivacyreasons*/" />\n' +
      '<meta property="article:modified_time" content="2021-07-29T13:50:31+00:00" />\n' +
      '<meta property="og:image" content="/*removedorprivacyreasons*/" />\n' +
      '\t<meta property="og:image:width" content="545" />\n' +
      '\t<meta property="og:image:height" content="254" />\n' +
      '<meta name="twitter:card" content="summary_large_image" />\n' +
      '<script type="application/ld+json" class="yoast-schema-graph">{"@context":"https://schema.org","@graph":[{"@type":"WebSite","@id":"/*removedorprivacyreasons*/","url":"/*removedorprivacyreasons*//","name":"/*removedorprivacyreasons*/","description":"Just another WordPress site","potentialAction":[{"@type":"SearchAction","target":"/*removedorprivacyreasons*//?s={search_term_string}","query-input":"required name=search_term_string"}],"inLanguage":"en-GB"},{"@type":"WebPage","@id":"/*removedorprivacyreasons*/","url":"/*removedorprivacyreasons*/","name":/*removedorprivacyreasons*//#website"},"datePublished":"2021-07-29T13:50:17+00:00","dateModified":"2021-07-29T13:50:31+00:00","breadcrumb":{"@id":"/*removedorprivacyreasons*/#breadcrumb"},"inLanguage":"en-GB","potentialAction":[{"@type":"ReadAction","target":["http://usresourcesgridsome.kinsta.cloud/wp-content/uploads/2021/07/test-featured-image.png"]}]},{"@type":"BreadcrumbList","@id":"/*removedorprivacyreasons*/#breadcrumb","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"http://usresourcesgridsome.kinsta.cloud/"},{"@type":"ListItem","position":2,"name":"Test blog 3","item":"/*removedorprivacyreasons*/"},{"@type":"ListItem","position":3,"name":"test-featured-image"}]}]}</script>\n' +     
      '',
    description: /*removedorprivacyreasons*/
    caption: '',
    altText: 'Test featured image',
    mediaType: 'image',
    mimeType: 'image/png',
    mediaDetails: [Object: null prototype] {
      width: 545,
      height: 254,
      file: '2021/07/test-featured-image.png',
      sizes: [Object: null prototype],
      imageMeta: [Object: null prototype]
    },
    post: 7542,
    sourceUrl: /*removedorprivacyreasons*/
  },
  acf: [Object: null prototype] {
    ukHrefLang: 'Uk href lang test',
    usHrefLang: '',
    heroTitle: 'Hero title test',
    heroText: '',
    readTime: '2',
    videoUrl: '',
    transcript: '',
    mostPopular: [ 'true' ]
  },
  type: 'post',
  categories: [
    [Object: null prototype] {
      id: '7',
      title: 'News',
      slug: 'news',
      content: '',
      count: 3,
      path: '/resources/category/news/'
    }
  ],
  tags: [
    [Object: null prototype] {
      id: '37',
      title: 'News',
      slug: 'news',
      content: '',
      count: 4,
      path: '/resources/tag/news/'
    },
    [Object: null prototype] {
      id: '38',
      title: 'Yoast',
      slug: 'yoast',
      content: '',
      count: 1,
      path: '/resources/tag/yoast/'
    }
  ],
  date: '2021-07-01T09:47:24',
  excerpt: '<p>Unique yoast data to find it easier</p>\n',
  content: '<p>Unique yoast data to find it easier</p>\n'
}

TypeError: gridsome.config.js: Cannot read property 'map' of undefined (132:45)

  130 |               return {
  131 |                 ...collection,
> 132 |                 authors: collection.authors.map(author => author.name)
      |                                             ^
  133 |               }
  134 |             }
  135 |

**Comment by thetre97** [comment]
Okay - so that shows author as an object, not an array? So you can't run an array method (like `map`) on an object...

**Comment by Samii-Noden** [comment]
Ah of course - so will I not be able to search on categories, tags, authors or acf? Or is there another way to include child objects within the parent object?

**Comment by thetre97** [comment]
You should be able to, just specifying 'author' in the search fields should automatically fetch the nested author object, and index it...

**Comment by Samii-Noden** [comment]
Hmmm - it's not working. It turns out that categories and tags are arrays so they are fine using the map method. I just can't search by author or advanced custom fields - they're both definitely in there

searchFields: [
          'title',
          'tags',
          'type',
          'author',
          'category',
          'excerpt',
          'content',
          'slug',
          'path',
          'sector',
          'acf',
        ],

**Comment by thetre97** [comment]
Hmm, okay - I'll take a look into this when I get a chance.

Incidentally, you could just return the authors name by using the function option - I.e. `author: collection.author.name`

**Comment by Samii-Noden** [comment]
I have no idea why I didn't think of that in the first place - that works for me and I'm happy to take that as a solution.

Thanks so much for your help!

**Comment by thetre97** [comment]
Great - I'll keep this open to remind me to check why it doesn't index nested objects, although it may be a flexsearch config needed.

**Comment by thetre97** [comment]
Think I may have a solution for this - like arrays, nested objects can be stringified, so Flexsearch will then parse that data as a string.

@Samii-Noden If you have time, would you be able to test out this fix (`v2.0.2`) to see if it works for you?

**Comment by Samii-Noden** [comment]
Yeah I can give it a test - so would it be a case of just specifying 'authors' in the searchFields array without having to do author: collection.author.name in the collection?

**Comment by thetre97** [comment]
Great, thanks 🙂 yes, that is correct...

Although bear in mind it will index every single field under author, so you may still want to filter out some fields by returning an object with the transform function - I.e.
```js
transform: collection => ({
	...collection,
	author: {
		name: collection.author.name,
		bio: collection.author.bio
	}
})
```

**Comment by Samii-Noden** [comment]
Thank you - that appears to work!
